### ISSUE TITLE
Method 

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/busra_efe_onboard#1]
Sayfa içerisindeki widgetların methodlara daha fazla ayırarak parçalamaya özen gösterelim. Bu widget bloguna daha parçalabiliyoruz
https://github.com/VBT-FlutterCamp/busra_efe_onboard/blob/6f35c8c9691b5a0b22a27391a3540001abe64499/lib/feature/onboard/view/onboard_view.dart#L60

**Comment by busraefee** [comment]
düzeltildi
