### ISSUE TITLE
Text static verilmemeli

### ISSUE THREAD

**Issue by Krdnzbyza** [VBT-FlutterCamp/busra_efe_onboard#2]
Proje içerisinde sayfadaki textlerimizi beraber yaptıgımız gibi  string dosyasından çekmeliyiz
https://github.com/VBT-FlutterCamp/busra_efe_onboard/blob/6f35c8c9691b5a0b22a27391a3540001abe64499/lib/feature/onboard/view/onboard_view.dart#L136

**Comment by busraefee** [comment]
düzeltildi
